### PR TITLE
fix(glimmer-wrapper): add `normalize` method for `Registry#has`

### LINKED ISSUE #299: MU resolver does not convert camelCase to kebap-case for `has` check
Basically a reprise of #195. Originally reported as https://github.com/ember-decorators/ember-decorators/issues/337.

Service injections that rely on the property key reflection don't work, if that key is camelCase, because the `glimmer-resolver` does not provide a [`normalize` method](https://github.com/ember-cli/ember-resolver/blob/7338be016b1312f41731956573e6bd8a84bcad68/mu-trees/addon/resolvers/glimmer-wrapper/index.js#L84).

- [`@ember/-internals/container/registry#validateInjections`](https://github.com/emberjs/ember.js/blob/f96a8df934fc8b4178f587b1cce609df15930922/packages/%40ember/-internals/container/lib/registry.ts#L732-L746)
- [`@ember/-internals/container/registry#has`](https://github.com/emberjs/ember.js/blob/f96a8df934fc8b4178f587b1cce609df15930922/packages/%40ember/-internals/container/lib/registry.ts#L385-L405)
- [`@ember/-internals/container/registry#normalizeFullName`](https://github.com/emberjs/ember.js/blob/f96a8df934fc8b4178f587b1cce609df15930922/packages/%40ember/-internals/container/lib/registry.ts#L334-L350)

Because of this, the raw specifier is just passed through as is, and `has` fails.

`validateInjections` is stripped from prod builds and since the _actual_ resolution works successfully (#206), this does not fail in production.
 
/cc @lolmaus @simonihmig

### PR DESCRIPTION
**Pull request by buschtoens**
Fixes #299.

### CODE REVIEW

File: mu-trees/addon/resolvers/glimmer-wrapper/index.js [hunk 1]
```diff
@@ -81,7 +81,15 @@ const Resolver = GlobalsResolver.extend({
     this._glimmerResolver = new GlimmerResolver(this.config, this.glimmerModuleRegistry);
   },
 
-  normalize: null,
+  normalize(specifier) {
```
Comment (rwjblue) [inline mu-trees/addon/resolvers/glimmer-wrapper/index.js]: Since this is only needed for debug builds, can you move the functionality to be added in debug builds only?

```js
import { DEBUG } from '@glimmer/env';

class Resolver {
  // existing stuff
}

if (DEBUG) {
  Resolver.prototype.normalize = function(specifier) {
    // implementation from this PR
  }
}
```

**Comment by lolmaus** [comment]
:bow:

**Comment by buschtoens** [comment]
Just tested the above fix in our app. It works. I'll send another PR.
